### ISSUE TITLE
Error after upgrading to 0.5.1

### ISSUE THREAD

**Issue by timothyblue** [radswiat/webpack-auto-inject-version#8]
I get the following error after upgrading.

Error: Cannot find module 'babel-runtime/helpers/classCallCheck'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at webpackUniversalModuleDefinition (C:\data\web\damage\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:3:28)
    at Object.<anonymous> (C:\data\web\damage\node_modules\webpack-auto-inject-version\dist\WebpackAutoInjectVersion.js:10:3)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\data\web\damage\config\webpack.common.js:5:25)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)

**Comment by radswiat** [comment]
I'm not sure if that will help, but can u please try with a latest version ?
If worst case, you can try to install:
```
"babel-cli": "^6.10.1",
"babel-core": "^6.24.1",
```
but it should not be necessary with a new 0.5.4 v
Thanks :)

**Comment by kidroca** [comment]
I'm getting the same error just now v0.5.4

Running the demo project
I haven't install the main (root) project dependencies - that fixed the issue
To run the demo you have to do `npm install` in root and `npm install` in ./demo

**Comment by radswiat** [comment]
I'll have to create a clear project to check this out - but it's a bid odd,
not sure how npm installs a package deps, will double check this later on,
thanks for the response!

**Comment by kidroca** [comment]
It's fine, It's just that I cloned the repo and went directly to the demo folder, installing the package from `npm` works as it should.

My problem occurred because the demo uses `../dist/WebpackAutoInjectVersion.js` this file depends on all the dependencies in the main `package.json` and I only ran `npm install` in `./demo`.

Anyway I think it's ok to have the ./demo/package.json have `webpack-auto-inject-version` as dependency
and use `require('webpack-auto-inject-version').default;` instead of `require('../dist/WebpackAutoInjectVersion').default;`

**Comment by radswiat** [comment]
not sure why demo package requires npm install at all,
its just an example how u can develop, it's useful for testing/adding features as u can switch between require from dist directly instead of pushing to npm every time u want to check if your change works.
One of the issue is that it was pushed as a dependency - that shouldn't happen,
Will double check that :) Thanks!

**Comment by kidroca** [comment]
The demo is an example how one would set up a real world project, yes? And since it has it's own package.json with it's dependencies you can run `npm install` to install them. 

You can probably run the demo without installing it's dependencies because they are covered from the parent package and `node` will look for node_modules in the parent folder recursively 

Anyway I reviewed package.json recent history and you moved some devDependencies (including babel related) to dependencies which should fix the original issue 

You can add the `demo` folder to `.npmignore` as right now it is distributed with the package and
that is not necessary if it's meant only for development 
Also the `tool` folder seems to be needed only for building the dist, and probably can also be added to `.npmignore`

**Comment by radswiat** [comment]
So i did some changes,
- all deps has moved to devDependecies as it take ages to install the package otherwise
- to prevent missing deps, webpack build is including node_modules and babel-polyfill which should fix the missing deps problem
- demo has been added to .npmignore but its still on github
- eslint added

Closing for now, hope it's gonna be ok now :)
